name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            CC: gcc
            CXX: g++
          - os: ubuntu-latest
            CC: clang
            CXX: clang++
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: prepare ${{matrix.CC}}
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_C_COMPILER:FILEPATH=${{matrix.CC}} -DCMAKE_CXX_COMPILER:FILEPATH=${{matrix.CXX}} -DCMAKE_CXX_FLAGS:STRING="-Wall" ..
    - name: build ${{matrix.CC}}
      run: |
        cd build
        make
    - name: test ${{matrix.CC}}
      run: |
        cd build
        ctest
    
