name: CI

on: [push]

jobs:
  build:
    runs-on: ${{matrix.os}}
    name: build ${{matrix.cc}}
    strategy:
      matrix:
        name: [ubuntu-latest-gcc, ubuntu-latest-clang]
        include:
          - name: ubuntu-latest-gcc
            os: ubuntu-latest
            cc: gcc-9
            cxx: g++-9
          - name: ubuntu-latest-clang
            os: ubuntu-latest
            cc: clang
            cxx: clang++
    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: prepare ${{matrix.cc}}
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_C_COMPILER:FILEPATH=${{matrix.cc}} -DCMAKE_CXX_COMPILER:FILEPATH=${{matrix.cxx}} -DCMAKE_CXX_FLAGS:STRING="-Wall" ..
    - name: build ${{matrix.cc}}
      run: |
        cd build
        make
    - name: test ${{matrix.cc}}
      run: |
        cd build
        ctest
    
