name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: prepare
      run: |
        pwd
        mkdir -p build
        cd build
        cmake ..
